name: dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.10.5=py310h5b4e0ec_0
  - aiosignal=1.3.1=pyhd8ed1ab_1
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alsa-lib=1.2.12=h4ab18f5_0
  - anyio=4.6.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py310ha75aee5_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - astroid=3.3.3=py310hff52083_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_1
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - asyncssh=2.17.0=pyhd8ed1ab_0
  - atomicwrites=1.4.1=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - attrs=24.2.0=pyh71513ae_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - babel=2.14.0=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.0.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_1
  - binaryornot=0.4.4=pyhd8ed1ab_2
  - black=24.8.0=py310hff52083_1
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.6=hef167b5_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hebfffa5_3
  - certifi=2025.1.31=py310h06a4308_0
  - cffi=1.17.1=py310h8deb56e_0
  - cftime=1.6.4=py310hf462985_1
  - chardet=5.2.0=py310hff52083_2
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_1
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.2.1=py310hd41b1e2_0
  - cookiecutter=2.6.0=pyhd8ed1ab_1
  - cryptography=43.0.1=py310h6c63255_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cython=3.0.11=py310h5b1441d_3
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.5=py310hf71b8c6_1
  - decorator=5.1.1=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.14=pyh1a96a4e_0
  - diff-match-patch=20230430=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - docstring-to-markdown=0.15=pyhd8ed1ab_1
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.0=h59595ed_0
  - emcee=3.1.6=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.3=h5888daf_0
  - fcitx-qt5=1.2.7=h51b374b_1
  - ffmpeg=7.1.0=gpl_h8657690_700
  - ffmpeg-python=0.2.0=pyhff2d567_1
  - flake8=7.1.1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.0=py310ha75aee5_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py310ha75aee5_1
  - future=1.0.0=pyhd8ed1ab_2
  - fzf=0.55.0=ha8f183a_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=hd590300_0
  - glib=2.80.3=h315aac3_2
  - glib-tools=2.80.3=h8fdd7da_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py310he8512ff_3
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstools=1.6.0=py310h5eaa309_1
  - gstreamer=1.24.7=hf3bb09a_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.1.0=pyhd8ed1ab_1
  - h5py=3.12.1=nompi_py310h60e0fe6_103
  - hankel=1.2.2=pyhd8ed1ab_1
  - harfbuzz=9.0.0=hda332d3_1
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_h2d575fe_108
  - hpack=4.0.0=pyhd8ed1ab_1
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_1
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_1
  - inflection=0.5.1=pyhd8ed1ab_1
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipympl=0.9.4=pyhd8ed1ab_1
  - ipython=8.27.0=pyh707e725_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipywidgets=8.1.5=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=5.13.2=pyhd8ed1ab_1
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=5.3.0=pyhd8ed1ab_2
  - jaraco.functools=4.0.0=pyhd8ed1ab_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jellyfish=1.1.0=py310h505e2c1_1
  - jinja2=3.1.4=pyhd8ed1ab_1
  - joblib=1.4.2=py310h06a4308_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_1
  - jupyter_server=2.14.2=pyhd8ed1ab_1
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_1
  - keyring=25.4.1=pyha804496_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=24_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=24_linux64_openblas
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp19.1=19.1.0=default_hb5137d0_0
  - libclang13=19.1.0=default_h9c6a7e4_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.21=h4bc722e_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgcrypt=1.11.0=h4ab18f5_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.80.3=h315aac3_2
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgomp=14.1.0=h77fa898_1
  - libgpg-error=1.50=h4f305b6_0
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=24_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.8=h8b73ec9_2
  - libllvm19=19.1.0=ha7bfdaf_0
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopengl=1.7.0=ha4b6fd6_0
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=16.4=h2d7952a_3
  - libprotobuf=5.28.2=h5b01275_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialindex=2.0.0=he02047a_0
  - libsqlite=3.46.1=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libsystemd0=256.6=h2774228_0
  - libtiff=4.7.0=h6565414_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=h8a09558_1
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.1=hac33072_0
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hb9d3cd8_1
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=he7c6b58_4
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.11.1=hf83b1b0_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.9.4=hcb278e6_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=2.1.5=py310ha75aee5_1
  - matplotlib=3.9.1=py310hff52083_2
  - matplotlib-base=3.9.1=py310hf02ac8c_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - meshio=5.3.5=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_1
  - more-itertools=10.5.0=pyhd8ed1ab_1
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.6=h59595ed_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.1.0=py310h89163eb_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_1
  - mysql-common=9.0.1=h266115a_4
  - mysql-libs=9.0.1=he0572af_4
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=hd8ed1ab_3
  - nbconvert-core=7.16.4=pyhd8ed1ab_3
  - nbconvert-pandoc=7.16.4=hd8ed1ab_3
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py310h9f0ad05_101
  - notebook=7.2.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.35=h27087fc_0
  - nss=3.104=hd34e28f_0
  - numpydoc=1.8.0=pyhd8ed1ab_1
  - ocl-icd=2.3.2=hb9d3cd8_2
  - opencl-headers=2024.10.24=h5888daf_0
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.4.0=h7b32b05_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py310hf9f9076_1
  - pandoc=3.4=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pathspec=0.12.1=pyhd8ed1ab_1
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py310he228d35_1
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.21.0=pyhd8ed1ab_1
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py310ha75aee5_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pyconify=0.1.6=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydocstyle=6.3.0=pyhd8ed1ab_1
  - pyevtk=1.6.0=pyhb0bfe47_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygithub=2.4.0=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_1
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pylint=3.3.0=pyhd8ed1ab_0
  - pylint-venv=3.0.3=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py310ha75aee5_4
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pyqtwebengine=5.15.9=py310h704022c_5
  - pyside6=6.7.2=py310hfd10a26_4
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.15=h4a871b0_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-gssapi=1.8.3=py310h98feede_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-lsp-black=2.0.0=pyhff2d567_1
  - python-lsp-jsonrpc=1.1.2=pyhff2d567_1
  - python-lsp-server=1.12.0=pyhff2d567_1
  - python-lsp-server-base=1.12.0=pyhd8ed1ab_1
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.10=5_cp310
  - pytoolconfig=1.2.5=pyhd8ed1ab_1
  - pytz=2024.2=pyhd8ed1ab_1
  - pyuca=1.2=pyhd8ed1ab_2
  - pyxdg=0.28=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h89163eb_2
  - pyzmq=26.2.0=py310h71f11fc_3
  - qdarkstyle=3.2.3=pyhd8ed1ab_1
  - qhull=2020.2=h434a139_5
  - qstylizer=0.2.3=pyhd8ed1ab_0
  - qt-main=5.15.8=h3155989_26
  - qt-webengine=5.15.8=h8f589be_8
  - qt6-main=6.7.2=hadfd74e_5
  - qtawesome=1.3.1=pyh9208f05_1
  - qtconsole=5.6.0=pyhd8ed1ab_0
  - qtconsole-base=5.6.0=pyha770c72_0
  - qtpy=2.4.1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_1
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.8.1=pyhd8ed1ab_0
  - rope=1.13.0=pyhd8ed1ab_1
  - rpds-py=0.20.0=py310h505e2c1_1
  - rtree=1.3.0=py310h8dc1cec_2
  - secretstorage=3.3.3=py310hff52083_3
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=74.1.2=pyhd8ed1ab_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.16.0=pyhd8ed1ab_1
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sphinx=8.0.2=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - spyder=6.0.1=pyh62a8a7d_3
  - spyder-kernels=3.0.2=unix_pyh707e725_0
  - spyder-notebook=0.6.1=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - superqt=0.6.7=pyhb6d5dde_1
  - svt-av1=2.2.1=h5888daf_0
  - sympy=1.13.2=pypyh2585a3b_103
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.0.0=hceb3a55_0
  - terminado=0.18.1=pyh0d859eb_0
  - text-unidecode=1.3=pyhd8ed1ab_2
  - textdistance=4.6.3=pyhd8ed1ab_1
  - three-merge=0.1.1=pyhd8ed1ab_1
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.13.2=pyha770c72_1
  - tornado=6.4.1=py310ha75aee5_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20240906=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2024a=h8827d51_1
  - ujson=5.10.0=py310hf71b8c6_1
  - unicodedata2=15.1.0=py310ha75aee5_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.2.3=pyhd8ed1ab_1
  - watchdog=5.0.2=py310hff52083_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.8.0=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - whatthepatch=1.0.6=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_1
  - wrapt=1.16.0=py310ha75aee5_1
  - wurlitzer=3.1.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=hb9d3cd8_2
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_2
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.19.3=hb9d3cd8_1
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yapf=0.40.1=pyhd8ed1ab_1
  - yarl=1.11.1=py310ha75aee5_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha39cb0e_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - geopandas==1.1.2
    - gmsh==4.15.0
    - jax==0.6.2
    - jaxlib==0.6.2
    - llvmlite==0.46.0
    - mfem==4.8.0.1
    - ml-dtypes==0.5.4
    - numba==0.63.1
    - numpy==2.2.6
    - opt-einsum==3.4.0
    - patsy==1.0.2
    - pygmsh==7.1.17
    - pyogrio==0.12.1
    - pyproj==3.7.1
    - scipy==1.15.3
    - shapely==2.1.2
    - statsmodels==0.14.6
    - tqdm==4.67.1
prefix: /home/jacopo/anaconda3/envs/dev
